[AllowList]
  Files = []
Paths = []
Regexes = [
  "TOKEN\": \"\\$\\{localEnv:GITHUB_PERSONAL_ACCESS_TOKEN\\}\"",
  "TOKEN\": \"\\$\\{localEnv:GITHUB_TOKEN\\}\"",
  "TOKEN\": \"\\$\\{localEnv:ARTIFACTORY_TOKEN\\}\"",
]
