plugins:
  - - npm
    - setRcToken: false
      publishFolder: "dist/@tylertech/tyler-icons"
  - conventional-commits
  - released
author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
baseBranch: version-1