name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
version-resolver:
  major:
    labels:
      - 'type: enhancement'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
  default: 'minor'

categories:
  - title: 'New'
    label: 'type: enhancement'
  - title: 'Bug Fixes'
    label: 'type: bug'
  - title: 'Documentation'
    label: 'type: documentation'
template: |
  # What's Changed
  $CHANGES
