name: auto-release

on:
  push:
    branches:
    - master

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
    # Drafts your next Release notes as Pull Requests are merged into "master"
    - uses: release-drafter/release-drafter@v5
      with:
        publish: false
        prerelease: false
        config-name: auto-release-config.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  changelog:
    name: Chanegelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: etcdigital/pull-request-changelog@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
