name: auto-drafter

on:
  push:
    branches:
      - master
    paths-ignore:
      - "package.json"
      - "package-lock.json"
      - "CHANGELOG.md"

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: auto-release-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
