name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
concurrency: auto-release-${{ github.ref }}

jobs:
  release:
    name: Build and Release
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-build-release.yml@v0.17.0
    with:
      PRODUCTION_RELEASE: ${{ github.ref == 'refs/heads/main' && contains(fromJson('["push", "workflow_dispatch"]'), github.event_name) }}
      PACKAGE_ASSETS_ENABLED: ${{ github.ref == 'refs/heads/main' && contains(fromJson('["push", "workflow_dispatch"]'), github.event_name) }}
      PACKAGE_ASSETS_ARCHIVE_PATH: "dist/deployment-assets.tar.gz"
    secrets:
      GITHUB_APP_ID: ${{ secrets.FORGE_AUTOBOT_ID }}
      GITHUB_APP_KEY: ${{ secrets.FORGE_AUTOBOT_SECRET }}
      NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}

  #TODO: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idoutputs
  #      Once workflows are out of beta: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#limitations
  publish-cdn:
    name: Publish Assets to CDN
    needs: release
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-publish-cloudfront-assets.yml@v0.17.0
    if: ${{ github.ref == 'refs/heads/main' && contains(fromJson('["push", "workflow_dispatch"]'), github.event_name) }}
    with:
      AWS_IAM_ROLE: "arn:aws:iam::505039608154:role/forge-prod-cdnmgmt-tyler-icons"
      AWS_REGION: "us-east-1"
      AWS_S3_BUCKET_NAME: "tylerforge-s3assets51e60022-1ols9p4m4dr5y"
      AWS_CLOUDFRONT_DISTRIBUTION_ID: "EDE7DVFI1X60B"
      MAX_CLOUDFRONT_INVALIDATIONS: 25
