name: Build Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-build-and-test.yml@v0.17.0
    secrets:
      NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
