name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.CORPDEV_GITHUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git log
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'push' }}
        with:
          fetch-depth: 0
      - name: Determine next version
        uses: paulhatch/semantic-version@v3.1.1
        id: semver
        if: ${{ github.event_name == 'push' }}
        with:
          branch: "master"
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
      - name: Run publish.ps1
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "GitHub Actions"
          build-scripts/publish.ps1 -VersionNumber "${{ steps.semver.outputs.version }}"
        shell: pwsh
    env:
      # Be sure to update these with the appropriate Github secrets for your team. Do not paste actual values here.
      ARTIFACTORY_PULL_REGISTRY: "${{ secrets.ARTIFACTORY_PULL_REGISTRY }}"
      ARTIFACTORY_NUGET_REGISTRY: "${{ secrets.CORPDEV_ARTIFACTORY_NUGET_REGISTRY }}"
      ARTIFACTORY_NPM_REGISTRY: "${{ secrets.CORPDEV_ARTIFACTORY_NPM_REGISTRY }}"
      ARTIFACTORY_PUSH_REGISTRY: "${{ secrets.CORPDEV_ARTIFACTORY_PUSH_REGISTRY }}"
      ARTIFACTORY_USERNAME: "${{ secrets.CORPDEV_ARTIFACTORY_USERNAME }}"
      ARTIFACTORY_PASSWORD: "${{ secrets.CORPDEV_ARTIFACTORY_PASSWORD }}"
      ARTIFACTORY_TOKEN: "${{ secrets.CORPDEV_ARTIFACTORY_TOKEN }}"
